export const GUI_LOAD_START = 'GUI_LOAD_START';
export const GUI_LOAD_END = 'GUI_LOAD_END';

export const BUDGET_LOAD = 'BUDGET_LOAD';
export const BUDGET_LOAD_SUCCESS = 'BUDGET_LOAD_SUCCESS';
export const BUDGET_LOAD_FAIL = 'BUDGET_LOAD_FAIL';